language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - curl -sS https://getcomposer.org/installer | php

install:
  - php composer.phar install --prefer-dist --no-interaction --no-progress

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage  
  
script:
  - php --version
  - cd TestCase
  - phpunit -d date.timezone=UTC --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
  
notifications:
  email: false